### PR TITLE
Polished version

### PR DESCRIPTION
**Pull request by yyaldin**
In your review, please consider the following:

Clarity and precision of the written content: Is the language clear and concise? Is the information provided accurate and relevant?
Efficiency and functionality of the code: Does the updated code perform its function as expected? Are there any areas where its efficiency could be improved?
When providing feedback, I kindly request you to highlight at least one aspect that, in your opinion, should be further refined or enhanced. Your insights will be instrumental in elevating the quality of our work.

### CODE REVIEW

**Comment by stankur** [comment]
I would say, for the code, it would be better to leave it the way as before so it only utilizes the parameters of the packages functions that we have explored in class, so there is no doubt that the code we have is legitimate.

**Comment by stankur** [comment]
but the explanatory comments are pretty nice, so if you want to add some comments describing what the code does in different parts, that would be great.

**Comment by yyaldin** [comment]
> I would say, for the code, it would be better to leave it the way as before so it only utilizes the functions and parameters of the packages functions that we have explored in class, so there is no doubt that the code we have is legitimate.

Which functions are problematic? Because all the functions are described in the documentation.

**Comment by stankur** [comment]
I think we can remove the "Histograms are effective visual aids when we want to understand the distribution of a variable. " part for conciseness since the target audience probably knows this info.

**Comment by stankur** [comment]
> > I would say, for the code, it would be better to leave it the way as before so it only utilizes the functions and parameters of the packages functions that we have explored in class, so there is no doubt that the code we have is legitimate.
> 
> Which functions are problematic? Because all the functions are described in the documentation.

I think all of them works fine, just that some are not used in tutorials and worksheets, so I think it makes more sense to just use the simpler ones we use in the worksheet/tutorial. My only concern is that the checkers think that we are not writing the code. Let me know what you think.

I guess for example like using the free-y scale, and subtitles. It does make it look much better, but just that we never used it in tutorials/worksheet. For the purpose of this assignment, in my opinion, I think it's better to just use things we have used before in worksheets/assignments

**Comment by yyaldin** [comment]
> > > I would say, for the code, it would be better to leave it the way as before so it only utilizes the functions and parameters of the packages functions that we have explored in class, so there is no doubt that the code we have is legitimate.
> > 
> > 
> > Which functions are problematic? Because all the functions are described in the documentation.
> 
> I think all of them works fine, just that some are not used in tutorials and worksheets, so I think it makes more sense to just use the simpler ones we use in the worksheet/tutorial. My only concern is that the checkers think that we are not writing the code. Let me know what you think.

If you are talking about the histogram code, the only new functions I used are: color = "black", theme_minimal() and subtitle = "Distribution of STG, SCG, STR, LPR, and PEG") +
        theme(legend.position = "none"). 
For bar graph: palette="Dark2" and theme_minimal() + 
        theme(legend.position = "none"). 
It's in documentation, I personally don't think that its big of an issue. I'll reduce the number of words in the document.

**Comment by stankur** [comment]
Okay then, I guess we could keep the change for the code. Semantically, I checked that they are performing as expected as before.

**Pull request closed without merging**
